CREATE TABLE [dbo].[PRESUPUESTO]
(
	[ID_PRESUPUESTO] INT NOT NULL PRIMARY KEY, 
    [ID_CATEGORIA] INT NOT NULL, 
    [VALOR] DECIMAL NOT NULL, 
    [DESCRIPCION] NVARCHAR(MAX) NULL, 
    CONSTRAINT [FK_PRESUPUESTO_ToTable] FOREIGN KEY ([ID_CATEGORIA]) REFERENCES [CATEGORIA]([ID_CATEGORIA])
)
